-- PropTrust schema

create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  bio text,
  company text,
  license text,
  rating numeric default 5,
  reviews_count integer default 0,
  avatar text,
  created_at timestamptz default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  agent_id bigint references public.agents(id),
  title text not null,
  description text,
  price numeric,
  bedrooms numeric,
  bathrooms numeric,
  sqft numeric,
  address text,
  city text,
  state text,
  zip text,
  lat numeric,
  lng numeric,
  type text,
  status text default 'available',
  images jsonb default '[]'::jsonb,
  features jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id text,
  sender_name text,
  receiver_id text,
  receiver_name text,
  property_id bigint references public.properties(id),
  property_title text,
  content text not null,
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id),
  buyer_id text,
  buyer_name text,
  agent_id bigint references public.agents(id),
  amount numeric,
  status text default 'escrow',
  milestones jsonb default '[]'::jsonb,
  current_milestone integer default 0,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text check (role in ('buyer', 'realtor')) default 'buyer',
  company text,
  license text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_properties_agent_id on public.properties(agent_id);
create index if not exists idx_messages_property_id on public.messages(property_id);
create index if not exists idx_transactions_property_id on public.transactions(property_id);
create index if not exists idx_profiles_role on public.profiles(role);

alter table public.profiles enable row level security;
-- Create policies only if they do not already exist to make schema idempotent
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies p
    WHERE p.policyname = 'Profiles are viewable by owner'
      AND p.schemaname = 'public'
      AND p.tablename = 'profiles'
  ) THEN
    CREATE POLICY "Profiles are viewable by owner"
      ON public.profiles FOR SELECT
      USING (auth.uid() = id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies p
    WHERE p.policyname = 'Profiles are insertable by owner'
      AND p.schemaname = 'public'
      AND p.tablename = 'profiles'
  ) THEN
    CREATE POLICY "Profiles are insertable by owner"
      ON public.profiles FOR INSERT
      WITH CHECK (auth.uid() = id);
  END IF;
END
$$;

DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1 FROM pg_policies p
    WHERE p.policyname = 'Profiles are updatable by owner'
      AND p.schemaname = 'public'
      AND p.tablename = 'profiles'
  ) THEN
    CREATE POLICY "Profiles are updatable by owner"
      ON public.profiles FOR UPDATE
      USING (auth.uid() = id);
  END IF;
END
$$;

-- Seed sample data (Nigerian market)
insert into public.agents (name, email, phone, bio, company, license, rating, reviews_count)
values
  ('Chioma Okafor', 'chioma@propconnect.ng', '+234-805-123-4567', 'Luxury property specialist with 10+ years in Lagos real estate market.', 'PropConnect Realty Ltd', 'RC-127433', 4.9, 128),
  ('Tunde Adeyemi', 'tunde@propconnect.ng', '+234-807-456-7890', 'Expert in Abuja residential and commercial properties.', 'Capital Properties', 'RC-089122', 4.7, 84),
  ('Zainab Ibrahim', 'zainab@propconnect.ng', '+234-803-789-0123', 'Investment properties and mixed-use developments across Nigeria.', 'Future Homes Ltd', 'RC-145690', 4.8, 102)
on conflict do nothing;

insert into public.properties (agent_id, title, description, price, bedrooms, bathrooms, sqft, address, city, state, zip, type, status, images, features)
values
  (1, 'Luxury Apartment in Ikoyi', 'Premium 4-bedroom penthouse with panoramic Lagos lagoon views, fully furnished with smart home features.', 850000000, 4, 3.5, 3200, '15 Bourdillon Road', 'Lagos', 'Lagos', 'LG101', 'apartment', 'available', '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop"]', '["Lagoon view","Swimming pool","24/7 Security","Smart home"]'),
  (2, 'Modern Apartment in Central Abuja', '3-bedroom contemporary apartment in prime Maitama district with world-class amenities and gated security.', 250000000, 3, 2.5, 1950, '89 Gimbiya Street', 'Abuja', 'FCT', 'AB900', 'apartment', 'available', '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop"]', '["Concierge service","Gym & Spa","24/7 Power"]'),
  (3, 'Estate Townhouse in Lekki Phase 1', '3-bedroom townhouse in gated residential estate with common gardens and backup power system.', 120000000, 3, 2.5, 1850, '12 Admiralty Road', 'Lagos', 'Lagos', 'LG106', 'townhouse', 'pending', '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop"]', '["Gated estate","Generator/Solar","Smart locks","Community center"]')
on conflict do nothing;

-- Seed messages (Nigerian context)
insert into public.messages (sender_id, sender_name, receiver_id, receiver_name, property_id, property_title, content)
values
  ('buyer-amaka','Amaka Umeh','agent-chioma','Chioma Okafor', 1, 'Luxury Apartment in Ikoyi', 'Hello Chioma — is the Ikoyi penthouse still available for viewing this weekend?'),
  ('agent-chioma','Chioma Okafor','buyer-amaka','Amaka Umeh', 1, 'Luxury Apartment in Ikoyi', 'Hi Amaka, yes it is available — I have slots on Saturday afternoon or Sunday morning.'),
  ('buyer-emeka','Emeka Nwosu','agent-tunde','Tunde Adeyemi', 2, 'Modern Apartment in Central Abuja', 'Could you confirm if the maintenance fee is monthly or annual?'),
  ('agent-tunde','Tunde Adeyemi','buyer-emeka','Emeka Nwosu', 2, 'Modern Apartment in Central Abuja', 'Maintenance fee is monthly and covers security and common area upkeep.')
on conflict do nothing;
