-- PropTrust schema

create table if not exists public.agents (
  id bigint generated by default as identity primary key,
  name text not null,
  email text,
  phone text,
  bio text,
  company text,
  license text,
  rating numeric default 5,
  reviews_count integer default 0,
  avatar text,
  created_at timestamptz default now()
);

create table if not exists public.properties (
  id bigint generated by default as identity primary key,
  agent_id bigint references public.agents(id),
  title text not null,
  description text,
  price numeric,
  bedrooms numeric,
  bathrooms numeric,
  sqft numeric,
  address text,
  city text,
  state text,
  zip text,
  lat numeric,
  lng numeric,
  type text,
  status text default 'available',
  images jsonb default '[]'::jsonb,
  features jsonb default '[]'::jsonb,
  created_at timestamptz default now()
);

create table if not exists public.messages (
  id bigint generated by default as identity primary key,
  sender_id text,
  sender_name text,
  receiver_id text,
  receiver_name text,
  property_id bigint references public.properties(id),
  property_title text,
  content text not null,
  read boolean default false,
  created_at timestamptz default now()
);

create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  property_id bigint references public.properties(id),
  buyer_id text,
  buyer_name text,
  agent_id bigint references public.agents(id),
  amount numeric,
  status text default 'escrow',
  milestones jsonb default '[]'::jsonb,
  current_milestone integer default 0,
  completed_at timestamptz,
  created_at timestamptz default now()
);

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  email text,
  full_name text,
  role text check (role in ('buyer', 'realtor')) default 'buyer',
  company text,
  license text,
  created_at timestamptz default now(),
  updated_at timestamptz default now()
);

create index if not exists idx_properties_agent_id on public.properties(agent_id);
create index if not exists idx_messages_property_id on public.messages(property_id);
create index if not exists idx_transactions_property_id on public.transactions(property_id);
create index if not exists idx_profiles_role on public.profiles(role);

alter table public.profiles enable row level security;

create policy "Profiles are viewable by owner"
  on public.profiles for select
  using (auth.uid() = id);

create policy "Profiles are insertable by owner"
  on public.profiles for insert
  with check (auth.uid() = id);

create policy "Profiles are updatable by owner"
  on public.profiles for update
  using (auth.uid() = id);

-- Seed sample data
insert into public.agents (name, email, phone, bio, company, license, rating, reviews_count)
values
  ('Ava Thompson', 'ava@proptrust.com', '555-210-8890', 'Luxury coastal specialist with 12 years of experience.', 'PropTrust Realty', 'LIC-AVT-7743', 4.9, 128),
  ('Marcus Lee', 'marcus@proptrust.com', '555-882-1133', 'First-time buyer guide and neighborhood expert.', 'Cityline Homes', 'LIC-ML-2281', 4.7, 84),
  ('Sophia Ramirez', 'sophia@proptrust.com', '555-771-9922', 'Modern condos and investment properties.', 'Skyline Partners', 'LIC-SR-5409', 4.8, 102)
on conflict do nothing;

insert into public.properties (agent_id, title, description, price, bedrooms, bathrooms, sqft, address, city, state, zip, type, status, images, features)
values
  (1, 'Seaside Modern Villa', 'Ocean views with floor-to-ceiling glass and private pool.', 1950000, 4, 3.5, 3200, '128 Ocean Crest', 'Santa Monica', 'CA', '90401', 'house', 'available', '["https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1200&h=800&fit=crop"]', '["Ocean view","Pool","Smart home"]'),
  (2, 'Downtown Loft Retreat', 'Open-plan loft with skyline views and concierge amenities.', 850000, 2, 2, 1350, '44 Market St', 'Chicago', 'IL', '60601', 'condo', 'available', '["https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=1200&h=800&fit=crop"]', '["Concierge","Gym","Skyline view"]'),
  (3, 'Riverside Townhome', 'Walkable riverside community with private rooftop deck.', 620000, 3, 2.5, 1850, '902 Riverwalk Ave', 'Austin', 'TX', '78701', 'townhouse', 'pending', '["https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1200&h=800&fit=crop"]', '["Rooftop deck","Garage","Smart locks"]')
on conflict do nothing;
